### ISSUE TITLE
Train with custom dataset

### ISSUE THREAD

**Issue by chatzianagnostis** [PRBonn/ContMAV#3]
Hi nice work!
Can you guide me how to create a custom dataset as cityscapes dataset format?
thank

**Comment by matteosodano** [comment]
Hey. Just follow what I did with Cityscapes in the folder `src/datasets`. Especially in the file `pytorch_dataset.py`. You just need a class for your custom dataset that builds on top of DatasetBase (I also created a CityscapesBase but that's not needed), and overrides (and adds) any method that you might need. That's it. Then in the file `src.prepare_data.py` you can import your dataset and add it to the `if` statement in line 18, otherwise your code would crash. That's it, as you don't explicitly see the dataset anymore. 

Good luck!
